### ISSUE TITLE
Newlines in text cause a crash

### ISSUE THREAD

**Issue by Lemmmy** [Lignumm/CCEmuX#6]
```
Exception in thread "main" java.lang.NullPointerException
	at net.ceriat.clgd.ccemux.graphics.Graphics.orphanInstanceBuffer(Graphics.java:237)
	at net.ceriat.clgd.ccemux.graphics.Graphics.createInstanceBuffer(Graphics.java:263)
	at net.ceriat.clgd.ccemux.ui.UIText.initTextBuffer(UIText.java:76)
	at net.ceriat.clgd.ccemux.ui.UIText.<init>(UIText.java:29)
	at net.ceriat.clgd.ccemux.ui.EmuUI.<init>(EmuUI.java:19)
	at net.ceriat.clgd.ccemux.CCEmuX.<init>(CCEmuX.java:108)
	at net.ceriat.clgd.ccemux.CCEmuX.main(CCEmuX.java:173)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)
```

**Comment by Lignumm** [comment]
Probably.
